-- MySQL Script generated by MySQL Workbench
-- Thu May  9 02:20:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_estaciona_facil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_estaciona_facil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_estaciona_facil` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_estaciona_facil` ;

-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_movimentacao` (
  `cod_movimento` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `modelo_carro` VARCHAR(20) NOT NULL,
  `data_hora_entrada` DATETIME NOT NULL,
  `data_hora_saida` DATETIME NULL DEFAULT NULL,
  `tempo_permanencia` INT(11) NULL DEFAULT NULL,
  `valor_pago` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_movimento`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_preco` (
  `cod_preco` INT(11) NOT NULL AUTO_INCREMENT,
  `valor_primeira_hora` DECIMAL(5,2) NOT NULL,
  `valor_demais_horas` DECIMAL(5,2) NOT NULL,
  `tempo_tolerancia` INT(11) NULL DEFAULT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_preco`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
